<?php

namespace Database\Seeders;

use App\Models\QuranSuras;
use Illuminate\Database\Seeder;

class QuranSurasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $quran_suras = [
            ['name' => 'الفاتحة', 'total_number_aya' => 7,],
            ['name' => 'البقرة', 'total_number_aya' => 286,],
            ['name' => 'آل عمران', 'total_number_aya' => 200,],
            ['name' => 'النساء', 'total_number_aya' => 176,],
            ['name' => 'المائدة', 'total_number_aya' => 120,],
            ['name' => 'الأنعام', 'total_number_aya' => 165,],
            ['name' => 'الأعراف', 'total_number_aya' => 206,],
            ['name' => 'الأنفال', 'total_number_aya' => 75,],
            ['name' => 'التوبة', 'total_number_aya' => 129,],
            ['name' => 'يونس', 'total_number_aya' => 109,],
            ['name' => 'هود', 'total_number_aya' => 123,],
            ['name' => 'يوسف', 'total_number_aya' => 111,],
            ['name' => 'الرعد', 'total_number_aya' => 43,],
            ['name' => 'إبراهيم', 'total_number_aya' => 52,],
            ['name' => 'الحجر', 'total_number_aya' => 99,],
            ['name' => 'النحل', 'total_number_aya' => 128,],
            ['name' => 'الإسراء', 'total_number_aya' => 111,],
            ['name' => 'الكهف', 'total_number_aya' => 110,],
            ['name' => 'مريم', 'total_number_aya' => 98,],
            ['name' => 'طه', 'total_number_aya' => 135,],
            ['name' => 'الأنبياء', 'total_number_aya' => 112,],
            ['name' => 'الحج', 'total_number_aya' => 78,],
            ['name' => 'المؤمنون', 'total_number_aya' => 118,],
            ['name' => 'النور', 'total_number_aya' => 64,],
            ['name' => 'الفرقان', 'total_number_aya' => 77,],
            ['name' => 'الشعراء', 'total_number_aya' => 227,],
            ['name' => 'النمل', 'total_number_aya' => 93,],
            ['name' => 'القصص', 'total_number_aya' => 88,],
            ['name' => 'العنكبوت', 'total_number_aya' => 69,],
            ['name' => 'الروم', 'total_number_aya' => 60,],
            ['name' => 'لقمان', 'total_number_aya' => 34,],
            ['name' => 'السجدة', 'total_number_aya' => 30,],
            ['name' => 'الأحزاب', 'total_number_aya' => 73,],
            ['name' => 'سبأ', 'total_number_aya' => 54,],
            ['name' => 'فاطر', 'total_number_aya' => 45,],
            ['name' => 'يس', 'total_number_aya' => 83,],
            ['name' => 'الصافات', 'total_number_aya' => 182,],
            ['name' => 'ص', 'total_number_aya' => 88,],
            ['name' => 'الزمر', 'total_number_aya' => 75,],
            ['name' => 'غافر', 'total_number_aya' => 85,],
            ['name' => 'فصلت', 'total_number_aya' => 54,],
            ['name' => 'الشورى', 'total_number_aya' => 53,],
            ['name' => 'الزخرف', 'total_number_aya' => 89,],
            ['name' => 'الدخان', 'total_number_aya' => 59,],
            ['name' => 'الجاثية', 'total_number_aya' => 37,],
            ['name' => 'الأحقاف', 'total_number_aya' => 35,],
            ['name' => 'محمد', 'total_number_aya' => 38,],
            ['name' => 'الفتح', 'total_number_aya' => 29,],
            ['name' => 'الحجرات', 'total_number_aya' => 18,],
            ['name' => 'ق', 'total_number_aya' => 45,],
            ['name' => 'الذاريات', 'total_number_aya' => 60,],
            ['name' => 'الطور', 'total_number_aya' => 49,],
            ['name' => 'النجم', 'total_number_aya' => 62,],
            ['name' => 'القمر', 'total_number_aya' => 55,],
            ['name' => 'الرحمن', 'total_number_aya' => 78,],
            ['name' => 'الواقعة', 'total_number_aya' => 96,],
            ['name' => 'الحديد', 'total_number_aya' => 29,],
            ['name' => 'المجادلة', 'total_number_aya' => 22,],
            ['name' => 'الحشر', 'total_number_aya' => 24,],
            ['name' => 'الممتحنة', 'total_number_aya' => 13,],
            ['name' => 'الصف', 'total_number_aya' => 14,],
            ['name' => 'الجمعة', 'total_number_aya' => 11,],
            ['name' => 'المنافقون', 'total_number_aya' => 11,],
            ['name' => 'التغابن', 'total_number_aya' => 18,],
            ['name' => 'الطلاق', 'total_number_aya' => 12,],
            ['name' => 'التحريم', 'total_number_aya' => 12,],
            ['name' => 'الملك', 'total_number_aya' => 30,],
            ['name' => 'القلم', 'total_number_aya' => 52,],
            ['name' => 'الحاقة', 'total_number_aya' => 52,],
            ['name' => 'المعارج', 'total_number_aya' => 44,],
            ['name' => 'نوح', 'total_number_aya' => 28,],
            ['name' => 'الجن', 'total_number_aya' => 28,],
            ['name' => 'المزمل', 'total_number_aya' => 20,],
            ['name' => 'المدثر', 'total_number_aya' => 56,],
            ['name' => 'القيامة', 'total_number_aya' => 40,],
            ['name' => 'الإنسان', 'total_number_aya' => 31,],
            ['name' => 'المرسلات', 'total_number_aya' => 50,],
            ['name' => 'النبأ', 'total_number_aya' => 40,],
            ['name' => 'النازعات', 'total_number_aya' => 46,],
            ['name' => 'عبس', 'total_number_aya' => 42,],
            ['name' => 'التكوير', 'total_number_aya' => 29,],
            ['name' => 'الإنفطار', 'total_number_aya' => 19,],
            ['name' => 'المطففين', 'total_number_aya' => 36,],
            ['name' => 'الإنشقاق', 'total_number_aya' => 25,],
            ['name' => 'البروج', 'total_number_aya' => 22,],
            ['name' => 'الطارق', 'total_number_aya' => 17,],
            ['name' => 'الأعلى', 'total_number_aya' => 19,],
            ['name' => 'الغاشية', 'total_number_aya' => 26,],
            ['name' => 'الفجر', 'total_number_aya' => 30,],
            ['name' => 'البلد', 'total_number_aya' => 20,],
            ['name' => 'الشمس', 'total_number_aya' => 15,],
            ['name' => 'الليل', 'total_number_aya' => 21,],
            ['name' => 'الضحى', 'total_number_aya' => 11,],
            ['name' => 'الشرح', 'total_number_aya' => 8,],
            ['name' => 'التين', 'total_number_aya' => 8,],
            ['name' => 'العلق', 'total_number_aya' => 19,],
            ['name' => 'القدر', 'total_number_aya' => 5,],
            ['name' => 'البينة', 'total_number_aya' => 8,],
            ['name' => 'الزلزلة', 'total_number_aya' => 8,],
            ['name' => 'العاديات', 'total_number_aya' => 11,],
            ['name' => 'القارعة', 'total_number_aya' => 11,],
            ['name' => 'التكاثر', 'total_number_aya' => 8,],
            ['name' => 'العصر', 'total_number_aya' => 3,],
            ['name' => 'الهمزة', 'total_number_aya' => 9,],
            ['name' => 'الفيل', 'total_number_aya' => 5,],
            ['name' => 'قريش', 'total_number_aya' => 4,],
            ['name' => 'الماعون', 'total_number_aya' => 7,],
            ['name' => 'الكوثر', 'total_number_aya' => 3,],
            ['name' => 'الكافرون', 'total_number_aya' => 6,],
            ['name' => 'النصر', 'total_number_aya' => 3,],
            ['name' => 'المسد', 'total_number_aya' => 5,],
            ['name' => 'الإخلاص', 'total_number_aya' => 4,],
            ['name' => 'الفلق', 'total_number_aya' => 5,],
            ['name' => 'الناس', 'total_number_aya' => 6,],
        ];

        foreach ($quran_suras as $quran_sura) {
            QuranSuras::create($quran_sura);
        }
    }
}
