<?php

namespace Database\Seeders;

use App\Models\QuranSuras;
use Illuminate\Database\Seeder;

class QuranSurasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $quran_suras = [
            ['name' => 'الفاتحة', 'quran_part_id' => 17, 'total_number_aya' => 7,],
            ['name' => 'البقرة', 'quran_part_id' => 16, 'total_number_aya' => 286,],
            ['name' => 'آل عمران', 'quran_part_id' => 19, 'total_number_aya' => 200,],
            ['name' => 'النساء', 'quran_part_id' => 20, 'total_number_aya' => 176,],
            ['name' => 'المائدة', 'quran_part_id' => 21, 'total_number_aya' => 120,],
            ['name' => 'الأنعام', 'quran_part_id' => 22, 'total_number_aya' => 165,],
            ['name' => 'الأعراف', 'quran_part_id' => 23, 'total_number_aya' => 206,],
            ['name' => 'الأنفال', 'quran_part_id' => 24, 'total_number_aya' => 75,],
            ['name' => 'التوبة', 'quran_part_id' => 25, 'total_number_aya' => 129,],
            ['name' => 'يونس', 'quran_part_id' => 26, 'total_number_aya' => 109,],
            ['name' => 'هود', 'quran_part_id' => 27, 'total_number_aya' => 123,],
            ['name' => 'يوسف', 'quran_part_id' => 28, 'total_number_aya' => 111,],
            ['name' => 'الرعد', 'quran_part_id' => 28, 'total_number_aya' => 43,],
            ['name' => 'إبراهيم', 'quran_part_id' => 28, 'total_number_aya' => 52,],
            ['name' => 'الحجر', 'quran_part_id' => 29, 'total_number_aya' => 99,],
            ['name' => 'النحل', 'quran_part_id' => 29, 'total_number_aya' => 128,],
            ['name' => 'الإسراء', 'quran_part_id' => 30, 'total_number_aya' => 111,],
            ['name' => 'الكهف', 'quran_part_id' => 30, 'total_number_aya' => 110,],
            ['name' => 'مريم', 'quran_part_id' => 31, 'total_number_aya' => 98,],
            ['name' => 'طه', 'quran_part_id' => 31, 'total_number_aya' => 135,],
            ['name' => 'الأنبياء', 'quran_part_id' => 32, 'total_number_aya' => 112,],
            ['name' => 'الحج', 'quran_part_id' => 32, 'total_number_aya' => 78,],
            ['name' => 'المؤمنون', 'quran_part_id' => 33, 'total_number_aya' => 118,],
            ['name' => 'النور', 'quran_part_id' => 33, 'total_number_aya' => 64,],
            ['name' => 'الفرقان', 'quran_part_id' => 34, 'total_number_aya' => 77,],
            ['name' => 'الشعراء', 'quran_part_id' => 34, 'total_number_aya' => 227,],
            ['name' => 'النمل', 'quran_part_id' => 35, 'total_number_aya' => 93,],
            ['name' => 'القصص', 'quran_part_id' => 35, 'total_number_aya' => 88,],
            ['name' => 'العنكبوت', 'quran_part_id' => 36, 'total_number_aya' => 69,],
            ['name' => 'الروم', 'quran_part_id' => 36, 'total_number_aya' => 60,],
            ['name' => 'لقمان', 'quran_part_id' => 36, 'total_number_aya' => 34,],
            ['name' => 'السجدة', 'quran_part_id' => 36, 'total_number_aya' => 30,],
            ['name' => 'الأحزاب', 'quran_part_id' => 37, 'total_number_aya' => 73,],
            ['name' => 'سبأ', 'quran_part_id' => 37, 'total_number_aya' => 54,],
            ['name' => 'فاطر', 'quran_part_id' => 37, 'total_number_aya' => 45,],
            ['name' => 'يس', 'quran_part_id' => 38, 'total_number_aya' => 83,],
            ['name' => 'الصافات', 'quran_part_id' => 38, 'total_number_aya' => 182,],
            ['name' => 'ص', 'quran_part_id' => 38, 'total_number_aya' => 88,],
            ['name' => 'الزمر', 'quran_part_id' => 39, 'total_number_aya' => 75,],
            ['name' => 'غافر', 'quran_part_id' => 39, 'total_number_aya' => 85,],
            ['name' => 'فصلت', 'quran_part_id' => 39, 'total_number_aya' => 54,],
            ['name' => 'الشورى', 'quran_part_id' => 40, 'total_number_aya' => 53,],
            ['name' => 'الزخرف', 'quran_part_id' => 40, 'total_number_aya' => 89,],
            ['name' => 'الدخان', 'quran_part_id' => 40, 'total_number_aya' => 59,],
            ['name' => 'الجاثية', 'quran_part_id' => 40, 'total_number_aya' => 37,],
            ['name' => 'الأحقاف', 'quran_part_id' => 41, 'total_number_aya' => 35,],
            ['name' => 'محمد', 'quran_part_id' => 41, 'total_number_aya' => 38,],
            ['name' => 'الفتح', 'quran_part_id' => 41, 'total_number_aya' => 29,],
            ['name' => 'الحجرات', 'quran_part_id' => 41, 'total_number_aya' => 18,],
            ['name' => 'ق', 'quran_part_id' => 41, 'total_number_aya' => 45,],
            ['name' => 'الذاريات', 'quran_part_id' => 42, 'total_number_aya' => 60,],
            ['name' => 'الطور', 'quran_part_id' => 42, 'total_number_aya' => 49,],
            ['name' => 'النجم', 'quran_part_id' => 42, 'total_number_aya' => 62,],
            ['name' => 'القمر', 'quran_part_id' => 42, 'total_number_aya' => 55,],
            ['name' => 'الرحمن', 'quran_part_id' => 42, 'total_number_aya' => 78,],
            ['name' => 'الواقعة', 'quran_part_id' => 42, 'total_number_aya' => 96,],
            ['name' => 'الحديد', 'quran_part_id' => 42, 'total_number_aya' => 29,],
            ['name' => 'المجادلة', 'quran_part_id' => 43, 'total_number_aya' => 22,],
            ['name' => 'الحشر', 'quran_part_id' => 43, 'total_number_aya' => 24,],
            ['name' => 'الممتحنة', 'quran_part_id' => 43, 'total_number_aya' => 13,],
            ['name' => 'الصف', 'quran_part_id' => 43, 'total_number_aya' => 14,],
            ['name' => 'الجمعة', 'quran_part_id' => 43, 'total_number_aya' => 11,],
            ['name' => 'المنافقون', 'quran_part_id' => 43, 'total_number_aya' => 11,],
            ['name' => 'التغابن', 'quran_part_id' => 43, 'total_number_aya' => 18,],
            ['name' => 'الطلاق', 'quran_part_id' => 43, 'total_number_aya' => 12,],
            ['name' => 'التحريم', 'quran_part_id' => 43, 'total_number_aya' => 12,],
            ['name' => 'الملك', 'quran_part_id' => 44, 'total_number_aya' => 30,],
            ['name' => 'القلم', 'quran_part_id' => 44, 'total_number_aya' => 52,],
            ['name' => 'الحاقة', 'quran_part_id' => 44, 'total_number_aya' => 52,],
            ['name' => 'المعارج', 'quran_part_id' => 44, 'total_number_aya' => 44,],
            ['name' => 'نوح', 'quran_part_id' => 44, 'total_number_aya' => 28,],
            ['name' => 'الجن', 'quran_part_id' => 44, 'total_number_aya' => 28,],
            ['name' => 'المزمل', 'quran_part_id' => 44, 'total_number_aya' => 20,],
            ['name' => 'المدثر', 'quran_part_id' => 44, 'total_number_aya' => 56,],
            ['name' => 'القيامة', 'quran_part_id' => 44, 'total_number_aya' => 40,],
            ['name' => 'الإنسان', 'quran_part_id' => 44, 'total_number_aya' => 31,],
            ['name' => 'المرسلات', 'quran_part_id' => 44, 'total_number_aya' => 50,],
            ['name' => 'النبأ', 'quran_part_id' => 45, 'total_number_aya' => 40,],
            ['name' => 'النازعات', 'quran_part_id' => 45, 'total_number_aya' => 46,],
            ['name' => 'عبس', 'quran_part_id' => 45, 'total_number_aya' => 42,],
            ['name' => 'التكوير', 'quran_part_id' => 45, 'total_number_aya' => 29,],
            ['name' => 'الإنفطار', 'quran_part_id' => 45, 'total_number_aya' => 19,],
            ['name' => 'المطففين', 'quran_part_id' => 45, 'total_number_aya' => 36,],
            ['name' => 'الإنشقاق', 'quran_part_id' => 45, 'total_number_aya' => 25,],
            ['name' => 'البروج', 'quran_part_id' => 45, 'total_number_aya' => 22,],
            ['name' => 'الطارق', 'quran_part_id' => 45, 'total_number_aya' => 17,],
            ['name' => 'الأعلى', 'quran_part_id' => 45, 'total_number_aya' => 19,],
            ['name' => 'الغاشية', 'quran_part_id' => 45, 'total_number_aya' => 26,],
            ['name' => 'الفجر', 'quran_part_id' => 45, 'total_number_aya' => 30,],
            ['name' => 'البلد', 'quran_part_id' => 45, 'total_number_aya' => 20,],
            ['name' => 'الشمس', 'quran_part_id' => 45, 'total_number_aya' => 15,],
            ['name' => 'الليل', 'quran_part_id' => 45, 'total_number_aya' => 21,],
            ['name' => 'الضحى', 'quran_part_id' => 45, 'total_number_aya' => 11,],
            ['name' => 'الشرح', 'quran_part_id' => 45, 'total_number_aya' => 8,],
            ['name' => 'التين', 'quran_part_id' => 45, 'total_number_aya' => 8,],
            ['name' => 'العلق', 'quran_part_id' => 45, 'total_number_aya' => 19,],
            ['name' => 'القدر', 'quran_part_id' => 45, 'total_number_aya' => 5,],
            ['name' => 'البينة', 'quran_part_id' => 45, 'total_number_aya' => 8,],
            ['name' => 'الزلزلة', 'quran_part_id' => 45, 'total_number_aya' => 8,],
            ['name' => 'العاديات', 'quran_part_id' => 45, 'total_number_aya' => 11,],
            ['name' => 'القارعة', 'quran_part_id' => 45, 'total_number_aya' => 11,],
            ['name' => 'التكاثر', 'quran_part_id' => 45, 'total_number_aya' => 8,],
            ['name' => 'العصر', 'quran_part_id' => 45, 'total_number_aya' => 3,],
            ['name' => 'الهمزة', 'quran_part_id' => 45, 'total_number_aya' => 9,],
            ['name' => 'الفيل', 'quran_part_id' => 45, 'total_number_aya' => 5,],
            ['name' => 'قريش', 'quran_part_id' => 45, 'total_number_aya' => 4,],
            ['name' => 'الماعون', 'quran_part_id' => 45, 'total_number_aya' => 7,],
            ['name' => 'الكوثر', 'quran_part_id' => 45, 'total_number_aya' => 3,],
            ['name' => 'الكافرون', 'quran_part_id' => 45, 'total_number_aya' => 6,],
            ['name' => 'النصر', 'quran_part_id' => 45, 'total_number_aya' => 3,],
            ['name' => 'المسد', 'quran_part_id' => 45, 'total_number_aya' => 5,],
            ['name' => 'الإخلاص', 'quran_part_id' => 45, 'total_number_aya' => 4,],
            ['name' => 'الفلق', 'quran_part_id' => 45, 'total_number_aya' => 5,],
            ['name' => 'الناس', 'quran_part_id' => 45, 'total_number_aya' => 6,],
        ];

        foreach ($quran_suras as $quran_sura) {
            QuranSuras::create($quran_sura);
        }
    }
}
